{"modules": [{"name": "XrdAnalysis.test.test_Reader", "nr_success": 1, "nr_failed": 0, "nr_error": 0, "testcases": [{"name": "test_request_mat", "result": "success"}]}, {"name": "XrdAnalysis.test.test_generator", "nr_success": 0, "nr_failed": 0, "nr_error": 1, "testcases": [{"name": "test_print_to_pdf", "result": "error", "error": {"message": "TypeError: test_print_to_pdf() missing 1 required positional argument: 'self'", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}]}}]}, {"name": "XrdAnalysis.test.test_h5File.TestH5File", "nr_success": 0, "nr_failed": 7, "nr_error": 1, "testcases": [{"name": "test_get_file_handle", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_h5File.py", "linenr": 24, "function": "test_get_file_handle", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_get_recipe_plot", "result": "error", "error": {"message": "FileNotFoundError: [WinError 2] Le fichier sp\u00e9cifi\u00e9 est introuvable: 'C:\\\\Users\\\\hang\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python36-32\\\\TestData'", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_h5File.py", "linenr": 18, "function": "test_get_recipe_plot", "line": "os.chdir(os.path.join(os.path.dirname(sys.argv[0]), 'TestData'))"}]}}, {"name": "test_get_scan_dict", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_h5File.py", "linenr": 27, "function": "test_get_scan_dict", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_get_scan_type", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_h5File.py", "linenr": 30, "function": "test_get_scan_type", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_read_data", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_h5File.py", "linenr": 36, "function": "test_read_data", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_read_raw", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_h5File.py", "linenr": 33, "function": "test_read_raw", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_recipe", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_h5File.py", "linenr": 12, "function": "test_recipe", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_set_recipe", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_h5File.py", "linenr": 39, "function": "test_set_recipe", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}]}, {"name": "XrdAnalysis.test.test_rawFile.TestRawFile", "nr_success": 0, "nr_failed": 5, "nr_error": 0, "testcases": [{"name": "test_get_scan_dict", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_rawFile.py", "linenr": 6, "function": "test_get_scan_dict", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_get_scan_type", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_rawFile.py", "linenr": 9, "function": "test_get_scan_type", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_read_conf", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_rawFile.py", "linenr": 12, "function": "test_read_conf", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_read_data", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_rawFile.py", "linenr": 15, "function": "test_read_data", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}, {"name": "test_sv_conf", "result": "failed", "error": {"message": "AssertionError: None", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_rawFile.py", "linenr": 18, "function": "test_sv_conf", "line": "self.fail()"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 666, "function": "fail", "line": "raise self.failureException(msg)"}]}}]}, {"name": "XrdAnalysis.test.test_rsmScan.TestRsmScan", "nr_success": 1, "nr_failed": 0, "nr_error": 1, "testcases": [{"name": "test_plot", "result": "error", "error": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\hang\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python36-32\\\\TestData\\\\004.raw'", "traceback": [{"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\unittest\\case.py", "linenr": 601, "function": "run", "line": "testMethod()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\test\\test_rsmScan.py", "linenr": 19, "function": "test_plot", "line": "s = Reader.RawFile(test_file).read_data()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\Reader.py", "linenr": 1395, "function": "__init__", "line": "self._scan_instance = self.create_scan_instance()"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\Reader.py", "linenr": 1401, "function": "create_scan_instance", "line": "self._scan_type = str(self.get_scan_type())"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\Reader.py", "linenr": 1412, "function": "get_scan_type", "line": "return self.get_scan_dict()['_TYPE']"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\Reader.py", "linenr": 1406, "function": "get_scan_dict", "line": "data_list = self.__str_data(self.file)"}, {"filename": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator\\XrdAnalysis\\Reader.py", "linenr": 1416, "function": "__str_data", "line": "with open(raw_file, 'rb') as fp:"}]}}, {"name": "test_stack_raw_data", "result": "success"}]}, {"name": "XrdAnalysis.test.test_square.TestSquare", "nr_success": 1, "nr_failed": 0, "nr_error": 0, "testcases": [{"name": "test_intensity_image", "result": "success"}]}, {"name": "XrdAnalysis.test.test_twoDXrdScan.TestTwoDScan", "nr_success": 5, "nr_failed": 0, "nr_error": 0, "testcases": [{"name": "test_correction", "result": "success"}, {"name": "test_display_save_image", "result": "success"}, {"name": "test_peak_search", "result": "success"}, {"name": "test_print_result_csv", "result": "success"}, {"name": "test_stack_raw_data", "result": "success"}]}], "metadata": {"command": "C:\\Users\\hang\\AppData\\Local\\Programs\\Python\\Python36-32\\python.exe -m nose --with-json-extended", "time": 1510673340.3953545, "cwd": "C:\\Users\\hang\\Documents\\GitHub\\foton_report_genarator"}}